/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Answer
 */
export interface Answer {
    /**
     * The id of the question
     * @type {number}
     * @memberof Answer
     */
    questionId: number;
    /**
     * The content of the answer
     * @type {string}
     * @memberof Answer
     */
    content: string;
}

/**
 * Check if a given object implements the Answer interface.
 */
export function instanceOfAnswer(value: object): value is Answer {
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function AnswerFromJSON(json: any): Answer {
    return AnswerFromJSONTyped(json, false);
}

export function AnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Answer {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'],
        'content': json['content'],
    };
}

export function AnswerToJSON(json: any): Answer {
    return AnswerToJSONTyped(json, false);
}

export function AnswerToJSONTyped(value?: Answer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'content': value['content'],
    };
}

