/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserWithRole } from './UserWithRole';
import {
    UserWithRoleFromJSON,
    UserWithRoleFromJSONTyped,
    UserWithRoleToJSON,
    UserWithRoleToJSONTyped,
} from './UserWithRole';

/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * The user who posted the comment
     * @type {UserWithRole}
     * @memberof Comment
     */
    user: UserWithRole;
    /**
     * The content of the comment
     * @type {string}
     * @memberof Comment
     */
    content: string;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserWithRoleFromJSON(json['user']),
        'content': json['content'],
    };
}

export function CommentToJSON(json: any): Comment {
    return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(value?: Comment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserWithRoleToJSON(value['user']),
        'content': value['content'],
    };
}

