/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * The content of the comment
     * @type {string}
     * @memberof CreateCommentDto
     */
    content: string;
    /**
     * The ID of the post
     * @type {string}
     * @memberof CreateCommentDto
     */
    postId: string;
}

/**
 * Check if a given object implements the CreateCommentDto interface.
 */
export function instanceOfCreateCommentDto(value: object): value is CreateCommentDto {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    return true;
}

export function CreateCommentDtoFromJSON(json: any): CreateCommentDto {
    return CreateCommentDtoFromJSONTyped(json, false);
}

export function CreateCommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'postId': json['postId'],
    };
}

export function CreateCommentDtoToJSON(json: any): CreateCommentDto {
    return CreateCommentDtoToJSONTyped(json, false);
}

export function CreateCommentDtoToJSONTyped(value?: CreateCommentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'postId': value['postId'],
    };
}

