/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationPostDto
 */
export interface NotificationPostDto {
    /**
     * Post ID
     * @type {string}
     * @memberof NotificationPostDto
     */
    id: string;
}

/**
 * Check if a given object implements the NotificationPostDto interface.
 */
export function instanceOfNotificationPostDto(value: object): value is NotificationPostDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function NotificationPostDtoFromJSON(json: any): NotificationPostDto {
    return NotificationPostDtoFromJSONTyped(json, false);
}

export function NotificationPostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationPostDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function NotificationPostDtoToJSON(json: any): NotificationPostDto {
    return NotificationPostDtoToJSONTyped(json, false);
}

export function NotificationPostDtoToJSONTyped(value?: NotificationPostDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

