/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPreview
 */
export interface PostPreview {
    /**
     * The unique identifier of the post
     * @type {string}
     * @memberof PostPreview
     */
    id: string;
    /**
     * The title of the post
     * @type {string}
     * @memberof PostPreview
     */
    title: string;
    /**
     * The description of the post
     * @type {string}
     * @memberof PostPreview
     */
    description: string;
    /**
     * The tags of the post
     * @type {Array<string>}
     * @memberof PostPreview
     */
    tags: Array<string>;
    /**
     * The date the post was created
     * @type {string}
     * @memberof PostPreview
     */
    createdAt: string;
}

/**
 * Check if a given object implements the PostPreview interface.
 */
export function instanceOfPostPreview(value: object): value is PostPreview {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function PostPreviewFromJSON(json: any): PostPreview {
    return PostPreviewFromJSONTyped(json, false);
}

export function PostPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'tags': json['tags'],
        'createdAt': json['createdAt'],
    };
}

export function PostPreviewToJSON(json: any): PostPreview {
    return PostPreviewToJSONTyped(json, false);
}

export function PostPreviewToJSONTyped(value?: PostPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'tags': value['tags'],
        'createdAt': value['createdAt'],
    };
}

