/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadNotificationDto
 */
export interface ReadNotificationDto {
    /**
     * Mark all notifications before this timestamp as read
     * @type {string}
     * @memberof ReadNotificationDto
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ReadNotificationDto interface.
 */
export function instanceOfReadNotificationDto(value: object): value is ReadNotificationDto {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function ReadNotificationDtoFromJSON(json: any): ReadNotificationDto {
    return ReadNotificationDtoFromJSONTyped(json, false);
}

export function ReadNotificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadNotificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
    };
}

export function ReadNotificationDtoToJSON(json: any): ReadNotificationDto {
    return ReadNotificationDtoToJSONTyped(json, false);
}

export function ReadNotificationDtoToJSONTyped(value?: ReadNotificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
    };
}

