/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefFeedbackCount
 */
export interface RefFeedbackCount {
    /**
     * Feedback Kind
     * @type {string}
     * @memberof RefFeedbackCount
     */
    kind: string;
    /**
     * Feedback Count
     * @type {number}
     * @memberof RefFeedbackCount
     */
    count: number;
}

/**
 * Check if a given object implements the RefFeedbackCount interface.
 */
export function instanceOfRefFeedbackCount(value: object): value is RefFeedbackCount {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function RefFeedbackCountFromJSON(json: any): RefFeedbackCount {
    return RefFeedbackCountFromJSONTyped(json, false);
}

export function RefFeedbackCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefFeedbackCount {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'count': json['count'],
    };
}

export function RefFeedbackCountToJSON(json: any): RefFeedbackCount {
    return RefFeedbackCountToJSONTyped(json, false);
}

export function RefFeedbackCountToJSONTyped(value?: RefFeedbackCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'count': value['count'],
    };
}

