/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleUser
 */
export interface SimpleUser {
    /**
     * The name of the user
     * @type {string}
     * @memberof SimpleUser
     */
    name: string;
}

/**
 * Check if a given object implements the SimpleUser interface.
 */
export function instanceOfSimpleUser(value: object): value is SimpleUser {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SimpleUserFromJSON(json: any): SimpleUser {
    return SimpleUserFromJSONTyped(json, false);
}

export function SimpleUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleUser {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SimpleUserToJSON(json: any): SimpleUser {
    return SimpleUserToJSONTyped(json, false);
}

export function SimpleUserToJSONTyped(value?: SimpleUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

