/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubAnswerCreateDto
 */
export interface SubAnswerCreateDto {
    /**
     * The id of the sub-question
     * @type {number}
     * @memberof SubAnswerCreateDto
     */
    subQuestionId: number;
    /**
     * The content of the sub-answer
     * @type {string}
     * @memberof SubAnswerCreateDto
     */
    content: string;
}

/**
 * Check if a given object implements the SubAnswerCreateDto interface.
 */
export function instanceOfSubAnswerCreateDto(value: object): value is SubAnswerCreateDto {
    if (!('subQuestionId' in value) || value['subQuestionId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SubAnswerCreateDtoFromJSON(json: any): SubAnswerCreateDto {
    return SubAnswerCreateDtoFromJSONTyped(json, false);
}

export function SubAnswerCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubAnswerCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'subQuestionId': json['subQuestionId'],
        'content': json['content'],
    };
}

export function SubAnswerCreateDtoToJSON(json: any): SubAnswerCreateDto {
    return SubAnswerCreateDtoToJSONTyped(json, false);
}

export function SubAnswerCreateDtoToJSONTyped(value?: SubAnswerCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subQuestionId': value['subQuestionId'],
        'content': value['content'],
    };
}

