/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFeedbackDto
 */
export interface UpdateFeedbackDto {
    /**
     * turn on feedback or not
     * @type {boolean}
     * @memberof UpdateFeedbackDto
     */
    flag: boolean;
}

/**
 * Check if a given object implements the UpdateFeedbackDto interface.
 */
export function instanceOfUpdateFeedbackDto(value: object): value is UpdateFeedbackDto {
    if (!('flag' in value) || value['flag'] === undefined) return false;
    return true;
}

export function UpdateFeedbackDtoFromJSON(json: any): UpdateFeedbackDto {
    return UpdateFeedbackDtoFromJSONTyped(json, false);
}

export function UpdateFeedbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFeedbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'flag': json['flag'],
    };
}

export function UpdateFeedbackDtoToJSON(json: any): UpdateFeedbackDto {
    return UpdateFeedbackDtoToJSONTyped(json, false);
}

export function UpdateFeedbackDtoToJSONTyped(value?: UpdateFeedbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'flag': value['flag'],
    };
}

