/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HasUnreadNotificationResponseDto
 */
export interface HasUnreadNotificationResponseDto {
    /**
     * Whether the user has unread notifications
     * @type {boolean}
     * @memberof HasUnreadNotificationResponseDto
     */
    hasUnreadNotifications: boolean;
}

/**
 * Check if a given object implements the HasUnreadNotificationResponseDto interface.
 */
export function instanceOfHasUnreadNotificationResponseDto(value: object): value is HasUnreadNotificationResponseDto {
    if (!('hasUnreadNotifications' in value) || value['hasUnreadNotifications'] === undefined) return false;
    return true;
}

export function HasUnreadNotificationResponseDtoFromJSON(json: any): HasUnreadNotificationResponseDto {
    return HasUnreadNotificationResponseDtoFromJSONTyped(json, false);
}

export function HasUnreadNotificationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HasUnreadNotificationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'hasUnreadNotifications': json['hasUnreadNotifications'],
    };
}

export function HasUnreadNotificationResponseDtoToJSON(json: any): HasUnreadNotificationResponseDto {
    return HasUnreadNotificationResponseDtoToJSONTyped(json, false);
}

export function HasUnreadNotificationResponseDtoToJSONTyped(value?: HasUnreadNotificationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasUnreadNotifications': value['hasUnreadNotifications'],
    };
}

