/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostFeedback
 */
export interface PostFeedback {
    /**
     * The feedback type
     * @type {string}
     * @memberof PostFeedback
     */
    kind: string;
    /**
     * The content of the feedback
     * @type {number}
     * @memberof PostFeedback
     */
    count: number;
    /**
     * The uset has pushed the feedback
     * @type {boolean}
     * @memberof PostFeedback
     */
    pushed: boolean;
}

/**
 * Check if a given object implements the PostFeedback interface.
 */
export function instanceOfPostFeedback(value: object): value is PostFeedback {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('pushed' in value) || value['pushed'] === undefined) return false;
    return true;
}

export function PostFeedbackFromJSON(json: any): PostFeedback {
    return PostFeedbackFromJSONTyped(json, false);
}

export function PostFeedbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostFeedback {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'count': json['count'],
        'pushed': json['pushed'],
    };
}

export function PostFeedbackToJSON(json: any): PostFeedback {
    return PostFeedbackToJSONTyped(json, false);
}

export function PostFeedbackToJSONTyped(value?: PostFeedback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'count': value['count'],
        'pushed': value['pushed'],
    };
}

