/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleCategory
 */
export interface SimpleCategory {
    /**
     * The name of the category
     * @type {string}
     * @memberof SimpleCategory
     */
    name: string;
    /**
     * The image path of the category
     * @type {string}
     * @memberof SimpleCategory
     */
    image: string;
}

/**
 * Check if a given object implements the SimpleCategory interface.
 */
export function instanceOfSimpleCategory(value: object): value is SimpleCategory {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function SimpleCategoryFromJSON(json: any): SimpleCategory {
    return SimpleCategoryFromJSONTyped(json, false);
}

export function SimpleCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'image': json['image'],
    };
}

export function SimpleCategoryToJSON(json: any): SimpleCategory {
    return SimpleCategoryToJSONTyped(json, false);
}

export function SimpleCategoryToJSONTyped(value?: SimpleCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'image': value['image'],
    };
}

