/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleQuestion
 */
export interface SimpleQuestion {
    /**
     * The order of the question
     * @type {number}
     * @memberof SimpleQuestion
     */
    order: number;
    /**
     * The title of the question
     * @type {string}
     * @memberof SimpleQuestion
     */
    viewContent: string;
}

/**
 * Check if a given object implements the SimpleQuestion interface.
 */
export function instanceOfSimpleQuestion(value: object): value is SimpleQuestion {
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('viewContent' in value) || value['viewContent'] === undefined) return false;
    return true;
}

export function SimpleQuestionFromJSON(json: any): SimpleQuestion {
    return SimpleQuestionFromJSONTyped(json, false);
}

export function SimpleQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'order': json['order'],
        'viewContent': json['viewContent'],
    };
}

export function SimpleQuestionToJSON(json: any): SimpleQuestion {
    return SimpleQuestionToJSONTyped(json, false);
}

export function SimpleQuestionToJSONTyped(value?: SimpleQuestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order': value['order'],
        'viewContent': value['viewContent'],
    };
}

