/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubQuestion } from './SubQuestion';
import {
    SubQuestionFromJSON,
    SubQuestionFromJSONTyped,
    SubQuestionToJSON,
    SubQuestionToJSONTyped,
} from './SubQuestion';

/**
 * 
 * @export
 * @interface SubAnswer
 */
export interface SubAnswer {
    /**
     * The question related to this answer
     * @type {SubQuestion}
     * @memberof SubAnswer
     */
    subQuestion: SubQuestion;
    /**
     * The content of the answer
     * @type {string}
     * @memberof SubAnswer
     */
    content: string;
}

/**
 * Check if a given object implements the SubAnswer interface.
 */
export function instanceOfSubAnswer(value: object): value is SubAnswer {
    if (!('subQuestion' in value) || value['subQuestion'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function SubAnswerFromJSON(json: any): SubAnswer {
    return SubAnswerFromJSONTyped(json, false);
}

export function SubAnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubAnswer {
    if (json == null) {
        return json;
    }
    return {
        
        'subQuestion': SubQuestionFromJSON(json['subQuestion']),
        'content': json['content'],
    };
}

export function SubAnswerToJSON(json: any): SubAnswer {
    return SubAnswerToJSONTyped(json, false);
}

export function SubAnswerToJSONTyped(value?: SubAnswer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subQuestion': SubQuestionToJSON(value['subQuestion']),
        'content': value['content'],
    };
}

