/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubQuestion
 */
export interface SubQuestion {
    /**
     * The order of the question
     * @type {number}
     * @memberof SubQuestion
     */
    order: number;
    /**
     * The title of the question
     * @type {string}
     * @memberof SubQuestion
     */
    viewContent: string;
}

/**
 * Check if a given object implements the SubQuestion interface.
 */
export function instanceOfSubQuestion(value: object): value is SubQuestion {
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('viewContent' in value) || value['viewContent'] === undefined) return false;
    return true;
}

export function SubQuestionFromJSON(json: any): SubQuestion {
    return SubQuestionFromJSONTyped(json, false);
}

export function SubQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubQuestion {
    if (json == null) {
        return json;
    }
    return {
        
        'order': json['order'],
        'viewContent': json['viewContent'],
    };
}

export function SubQuestionToJSON(json: any): SubQuestion {
    return SubQuestionToJSONTyped(json, false);
}

export function SubQuestionToJSONTyped(value?: SubQuestion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order': value['order'],
        'viewContent': value['viewContent'],
    };
}

