/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubQuestionDto
 */
export interface SubQuestionDto {
    /**
     * The unique identifier of the question
     * @type {number}
     * @memberof SubQuestionDto
     */
    id: number;
    /**
     * The order of the question
     * @type {number}
     * @memberof SubQuestionDto
     */
    order: number;
    /**
     * The question
     * @type {string}
     * @memberof SubQuestionDto
     */
    content: string;
    /**
     * The description of the question
     * @type {string}
     * @memberof SubQuestionDto
     */
    description: string;
    /**
     * The minimum number of characters of the question
     * @type {number}
     * @memberof SubQuestionDto
     */
    minimum: number;
}

/**
 * Check if a given object implements the SubQuestionDto interface.
 */
export function instanceOfSubQuestionDto(value: object): value is SubQuestionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('minimum' in value) || value['minimum'] === undefined) return false;
    return true;
}

export function SubQuestionDtoFromJSON(json: any): SubQuestionDto {
    return SubQuestionDtoFromJSONTyped(json, false);
}

export function SubQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'order': json['order'],
        'content': json['content'],
        'description': json['description'],
        'minimum': json['minimum'],
    };
}

export function SubQuestionDtoToJSON(json: any): SubQuestionDto {
    return SubQuestionDtoToJSONTyped(json, false);
}

export function SubQuestionDtoToJSONTyped(value?: SubQuestionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'order': value['order'],
        'content': value['content'],
        'description': value['description'],
        'minimum': value['minimum'],
    };
}

