/* tslint:disable */
/* eslint-disable */
/**
 * Patient Voice API
 * Patient Voice service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserWithRole
 */
export interface UserWithRole {
    /**
     * The name of the user
     * @type {string}
     * @memberof UserWithRole
     */
    name: string;
    /**
     * The role of the user
     * @type {string}
     * @memberof UserWithRole
     */
    role: string;
}

/**
 * Check if a given object implements the UserWithRole interface.
 */
export function instanceOfUserWithRole(value: object): value is UserWithRole {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function UserWithRoleFromJSON(json: any): UserWithRole {
    return UserWithRoleFromJSONTyped(json, false);
}

export function UserWithRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithRole {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'role': json['role'],
    };
}

export function UserWithRoleToJSON(json: any): UserWithRole {
    return UserWithRoleToJSONTyped(json, false);
}

export function UserWithRoleToJSONTyped(value?: UserWithRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'role': value['role'],
    };
}

